// <auto-generated />
using System;
using AuctionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuctionApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuctionApi.Core.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("Attachments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuctionId = 1,
                            ContentType = "image/jpeg",
                            FileName = "Vase with Flowers.jpg",
                            FileSize = 3014991L,
                            StoredFileName = "vase-with-flowers.jpg",
                            UploadedAt = new DateTime(2026, 5, 20, 12, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AuctionId = 2,
                            ContentType = "image/jpeg",
                            FileName = "The Threatened Swan.jpg",
                            FileSize = 4674966L,
                            StoredFileName = "the-threatened-swan.jpg",
                            UploadedAt = new DateTime(2026, 5, 25, 10, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AuctionId = 3,
                            ContentType = "image/jpeg",
                            FileName = "In the Month of July.jpg",
                            FileSize = 6042351L,
                            StoredFileName = "in-the-month-of-july.jpg",
                            UploadedAt = new DateTime(2026, 6, 1, 14, 5, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Auctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A delicate floral still life watercolor on paper by Pieter van Loo (Haarlem 1735–1784). Van Loo was a respected member of the Haarlem Painters' Guild, officially registered as a 'painter of flowers.' This classical Dutch botanical painting depicts a richly arranged bouquet in a vase, showcasing van Loo's meticulous attention to botanical detail and his mastery of the watercolor medium. Comparable works by van Loo have sold at European auctions in the range of €5,000–€15,000.",
                            EndDate = new DateTime(2026, 7, 15, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 5, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 8500.00m,
                            Title = "Vase with Flowers — Pieter van Loo (c. 1745–1784)",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "A dramatic allegorical masterpiece of the Dutch Golden Age by Jan Asselijn (c. 1610–1652). Painted in oil on canvas around 1650, this life-sized depiction of a swan fiercely defending its nest has become one of the most iconic paintings in the Rijksmuseum collection. The work has been interpreted as a political allegory of the Dutch Republic defending itself against its enemies. As a national treasure of the Netherlands held in the Rijksmuseum, this painting is considered virtually priceless. Auction estimates for comparable Dutch Golden Age masterworks by major artists range from $2,000,000 to $5,000,000+.",
                            EndDate = new DateTime(2026, 8, 1, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 5, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 2200000.00m,
                            Title = "The Threatened Swan — Jan Asselijn (c. 1650)",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A tranquil landscape masterpiece by Paul Joseph Constantin Gabriël (1828–1903), a leading painter of the Hague School, often referred to as Dutch Impressionism. This oil on canvas (102 x 66 cm) from c. 1889 is one of the most celebrated Dutch landscape paintings of the 19th century and is part of the Rijksmuseum's permanent collection. The painting captures a quintessential Dutch polder scene with a windmill under a luminous sky. Gabriël's works have achieved auction prices ranging from €15,000 for smaller studies to €132,000 for major canvases, with this being among his finest.",
                            EndDate = new DateTime(2026, 8, 10, 20, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            StartDate = new DateTime(2026, 6, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            StartingPrice = 45000.00m,
                            Title = "A Windmill on a Polder Waterway, 'In the Month of July' — Paul Joseph Constantin Gabriël (c. 1889)",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BidDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10000.00m,
                            AuctionId = 1,
                            BidDate = new DateTime(2026, 5, 22, 14, 30, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Amount = 12500.00m,
                            AuctionId = 1,
                            BidDate = new DateTime(2026, 5, 25, 9, 15, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 2500000.00m,
                            AuctionId = 2,
                            BidDate = new DateTime(2026, 5, 28, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50000.00m,
                            AuctionId = 3,
                            BidDate = new DateTime(2026, 6, 3, 16, 45, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Amount = 62500.00m,
                            AuctionId = 3,
                            BidDate = new DateTime(2026, 6, 5, 10, 20, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@auctionlabb.com",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$2TTWZl03PadLy6RCW70WlOmuz8F1FqPupNCOePA7gdOF/gl97ZRwu",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "curator@auctionlabb.com",
                            IsActive = true,
                            Name = "Gallery Curator",
                            PasswordHash = "$2a$11$2TTWZl03PadLy6RCW70WlOmuz8F1FqPupNCOePA7gdOF/gl97ZRwu",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "collector@auctionlabb.com",
                            IsActive = true,
                            Name = "Art Collector",
                            PasswordHash = "$2a$11$2TTWZl03PadLy6RCW70WlOmuz8F1FqPupNCOePA7gdOF/gl97ZRwu",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Attachment", b =>
                {
                    b.HasOne("AuctionApi.Core.Entities.Auction", "Auction")
                        .WithMany("Attachments")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Auction", b =>
                {
                    b.HasOne("AuctionApi.Core.Entities.User", "User")
                        .WithMany("Auctions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Bid", b =>
                {
                    b.HasOne("AuctionApi.Core.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuctionApi.Core.Entities.User", "User")
                        .WithMany("Bids")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.Auction", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Bids");
                });

            modelBuilder.Entity("AuctionApi.Core.Entities.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
